# .travis.yml using container-based infrastructure

# use c as catch-all language
language: c

# use containers
sudo: false

# only run for pushes to master branch
branches:
  only:
   - master

# define environmental variables for R CMD check
env:
  global:
   - _R_CHECK_CRAN_INCOMING_=FALSE
   
before_install:
  - export PATH=$HOME/bin:$HOME/texlive/bin/x86_64-linux:$PATH
  - export PYTHONPATH=$HOME/python
  - export PYTHONUSERBASE=$HOME/python
  - export PREFIX_PATH=$HOME/python

# install r-base-dev:
# use r-packages-precise (https://cran.r-project.org/bin/linux/ubuntu/precise/) as source
# which is white listed (https://github.com/travis-ci/apt-source-whitelist/)
# also install latex, pandoc, qpdf and valgrind
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended
    - texinfo
    - lmodern
    - qpdf
    - valgrind
    - libblas3gf
    - libblas-dev
    - liblapack3gf
    - liblapack-dev
    - python-dev
    - python-pip

# cache local R libraries directory:
cache:
  directories:
    - $HOME/Rlib
    - $HOME/texlive
    - $HOME/bin
    - $HOME/python

# install the package and dependencies:
# use Yihue's compiled texlive and pandoc versions (https://github.com/yihui/knitR/blob/master/.travis.yml)
install:
  - mkdir -p $HOME/python
  - pip install petsc --allow-external petsc --install-option="--prefix=$PREFIX_PATH"
  - export PETSC_DIR=$PREFIX_PATH/lib/python2.7/site-packages/petsc
  - "[ ! -d ~/bin ] && mkdir ~/bin || true"
  - "wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-texlive | bash"
  - "wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-pandoc | bash"
  - mkdir -p ~/Rlib
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - echo '.travis.yml' > .Rbuildignore
  - Rscript -e 'if(!"devtools" %in% rownames(installed.packages())) { install.packages("devtools", dependencies=TRUE, repos="http://cran.rstudio.com/", lib="~/Rlib") }'
  - Rscript -e 'if(!"testthat" %in% rownames(installed.packages())) { install.packages("testthat", dependencies=TRUE, repos="http://cran.rstudio.com/", lib="~/Rlib") }'
  - Rscript -e 'if(!"covr" %in% rownames(installed.packages())) { install.packages("covr", dependencies=TRUE, repos="http://cran.rstudio.com/", lib="~/Rlib") }'
  - Rscript -e 'update.packages(ask = FALSE, instlib = "~/Rlib")'
  - Rscript -e 'devtools::install_deps(pkg = ".", dependencies = TRUE)'

# build, check, and install package
# run all examples through valgrind
script:
  - R CMD build . 
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
  - R CMD check "${PKG_FILE_NAME}" --as-cran 
  - R CMD INSTALL "${PKG_FILE_NAME}"
  - R -d valgrind --no-save < taoR.Rcheck/taoR-Ex.R
  - R -d valgrind --no-save < demo/test.R

# report coverage rate to coveralls
after_success:
  - Rscript -e 'covr::coveralls(exclusions = list("src/RcppExports.cpp", "R/zzz.R"))'

# send e-mails if stuff changes
notifications:
  email:
    on_success: change
    on_failure: change
